<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkillsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skills = [
            'HTML',
            'CSS',
            'JavaScript',
            'PHP',
            'Laravel',
            'Symfony',
            'React',
            'Vue',
            'Angular',
            'Node',
            'Express',
            'MongoDB',
            'MySQL',
            'PostgreSQL',
            'SQLite',
            'MariaDB',
            'Oracle',
            'SQL Server',
            'C',
            'C++',
            'C#',
            'Java',
            'Python',
            'Ruby',
            'Swift',
            'Kotlin',
            'Dart',
            'Go',
            'Rust',
            'Scala',
            'Haskell',
            'Perl',
            'R',
            'TypeScript',
            'Elixir',
            'Clojure',
            'F#',
            'Erlang',
            'Lua',
            'Julia',
            'Rust',
            'Shell',
            'PowerShell',
            'Bash',
            'Zsh',
            'Fish',
            'Ksh',
            'Tcsh',
            'Awk',
            'Sed',
            'Vim',
            'Emacs',
            'Nano',
            'Sublime Text',
            'VS Code',
            'Atom',
            'Eclipse',
            'NetBeans',
            'IntelliJ',
            'PyCharm',
            'WebStorm',
            'CLion',
            'Rider',
            'DataGrip',
            'GoLand',
            'AppCode',
            'RubyMine',
            'PhpStorm',
            'Android Studio',
            'Xcode',
            'Visual Studio',
            'Visual Studio Code',
            'Eclipse',
            'NetBeans',
            'IntelliJ',
            'PyCharm',
            'WebStorm',
            'CLion',
            'Rider',
            'DataGrip',
            'GoLand',
            'AppCode',
            'RubyMine',
            'PhpStorm',
            'Android Studio',
            'Xcode',
            'Visual Studio',
            'Visual Studio Code',
            'Eclipse',
            'NetBeans',
            'IntelliJ',
            'PyCharm',
            'WebStorm',
            'CLion',
            'Rider',
            'DataGrip',
            'GoLand',
            'AppCode',
            'RubyMine',
            'PhpStorm',
            'Android Studio',
            'Project Management',
            'Web Development',
            'Graphic Design',
            'UI/UX Design',
            'Mobile Development',
            'Game Development',
            'Data Science',
            'Communication',
            'Teamwork',
            'Problem-solving',
            'Time Management',
            'Leadership',
            'Adaptability',
            'Creativity',
            'Work Ethic',
            'Interpersonal Skills',
            'Critical Thinking',
            'Conflict Resolution',
            'Negotiation',
            'Decision Making',
            'Emotional Intelligence',
            'Stress Management',
            'Empathy',
            'Patience',
            'Persuasion',
            'Active Listening',
            'Networking',
            ];
        foreach ($skills as $skill) {
            Skill::create([
                'name' => $skill,
            ]);
        }
    }
}
